import { Component, OnInit, AfterViewInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';
import { switchMap } from 'rxjs/operators';

@Component({
  selector: 'app-tables',
  templateUrl: './tables.component.html',
  styleUrls: ['./tables.component.css']
})
export class TablesComponent implements OnInit {

  num = 5;
  data: Sample[] = [];
  constructor(private http: HttpClient, private router: Router, private route: ActivatedRoute) { }

  ngOnInit() {
    // $(document).ready(function () {
    //   $('#dataTable').datatable();
    // });

    this.route.queryParamMap.subscribe(params => {
      if (params.has('num')) {
        this.num = +params.get('num');
      }
    });

    this.http.get('http://www.mocky.io/v2/5c9e523f3000005500ee97cf')
      .subscribe((data: Sample[]) => {
        this.data = data;
        // setTimeout(() => { $('#dataTable').DataTable(); }, 0)
      });

    this.route
  }
  onChange(event: Event) {
    this.num = +(<HTMLSelectElement>event.target).value;
  }
}


// Generated by https://quicktype.io

export interface Sample {
  Name: string;
  Position: string;
  Office: string;
  Age: string;
  "Start date": string;
  Salary: string;
}

